# Form implementation generated from reading ui file 'arabaişlemleri.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class arabaislemleri(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(639, 502)
        Form.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(85, 83, 84, 255), stop:1 rgba(255, 255, 255,110));")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(521, 431))
        self.widget.setObjectName("widget")
        self.kaydet = QtWidgets.QPushButton(parent=self.widget)
        self.kaydet.setGeometry(QtCore.QRect(200, 300, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        self.kaydet.setFont(font)
        self.kaydet.setStyleSheet("QPushButton#kaydet{\n"
"    background-color: rgb(255, 255, 0);\n"
"    background-color: rgb(0, 126, 189);\n"
"\n"
"}\n"
"\n"
"QPushButton#kaydet:pressed{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.kaydet.setObjectName("kaydet")
        self.plaka = QtWidgets.QLineEdit(parent=self.widget)
        self.plaka.setGeometry(QtCore.QRect(150, 70, 221, 41))
        self.plaka.setText("")
        self.plaka.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.plaka.setObjectName("plaka")
        self.sira = QtWidgets.QLineEdit(parent=self.widget)
        self.sira.setGeometry(QtCore.QRect(150, 130, 221, 41))
        self.sira.setText("")
        self.sira.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.sira.setObjectName("sira")
        self.tutar = QtWidgets.QLineEdit(parent=self.widget)
        self.tutar.setGeometry(QtCore.QRect(150, 250, 221, 41))
        self.tutar.setText("")
        self.tutar.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tutar.setObjectName("tutar")
        self.yapilanislemler = QtWidgets.QLineEdit(parent=self.widget)
        self.yapilanislemler.setGeometry(QtCore.QRect(150, 190, 221, 41))
        self.yapilanislemler.setText("")
        self.yapilanislemler.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.yapilanislemler.setObjectName("yapilanislemler")
        self.verticalLayout.addWidget(self.widget, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.kaydet.setText(_translate("Form", "Kaydet"))
        self.plaka.setPlaceholderText(_translate("Form", "Plaka"))
        self.sira.setPlaceholderText(_translate("Form", "Sırası"))
        self.tutar.setPlaceholderText(_translate("Form", "Tutar"))
        self.yapilanislemler.setPlaceholderText(_translate("Form", "Yapılan İşlemler"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = arabaislemleri()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
