# Form implementation generated from reading ui file 'arabasil.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class arabasil(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(526, 457)
        Form.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(85, 83, 84, 255), stop:1 rgba(255, 255, 255,110));")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setMinimumSize(QtCore.QSize(508, 439))
        self.widget.setObjectName("widget")
        self.plaka = QtWidgets.QLineEdit(parent=self.widget)
        self.plaka.setGeometry(QtCore.QRect(160, 130, 221, 41))
        self.plaka.setText("")
        self.plaka.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.plaka.setObjectName("plaka")
        self.sil = QtWidgets.QPushButton(parent=self.widget)
        self.sil.setGeometry(QtCore.QRect(220, 190, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        self.sil.setFont(font)
        self.sil.setStyleSheet("QPushButton#sil{\n"
"    background-color: rgb(255, 255, 0);\n"
"    background-color: rgb(0, 126, 189);\n"
"\n"
"}\n"
"\n"
"QPushButton#sil:pressed{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.sil.setObjectName("sil")
        self.verticalLayout.addWidget(self.widget, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.plaka.setPlaceholderText(_translate("Form", "Plaka"))
        self.sil.setText(_translate("Form", "Sil"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = arabasil()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
