# Form implementation generated from reading ui file 'musterigörmesi.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

import resources
class musterigormesi(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(599, 435)
        Form.setStyleSheet("#Form{\n"
"border-image: url(:/a/tamir3.jpg);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setMinimumSize(QtCore.QSize(581, 417))
        self.widget.setObjectName("widget")
        self.plaka = QtWidgets.QLabel(parent=self.widget)
        self.plaka.setGeometry(QtCore.QRect(200, 160, 141, 31))
        self.plaka.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.plaka.setObjectName("plaka")
        self.logo = QtWidgets.QLabel(parent=self.widget)
        self.logo.setGeometry(QtCore.QRect(170, 90, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(20)
        font.setBold(False)
        self.logo.setFont(font)
        self.logo.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(85, 83, 84, 255), stop:1 rgba(255, 255, 255,110));")
        self.logo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.logo.setWordWrap(True)
        self.logo.setObjectName("logo")
        self.sirasi = QtWidgets.QLabel(parent=self.widget)
        self.sirasi.setGeometry(QtCore.QRect(200, 200, 141, 31))
        self.sirasi.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sirasi.setObjectName("sirasi")
        self.yapilanislemler = QtWidgets.QLabel(parent=self.widget)
        self.yapilanislemler.setGeometry(QtCore.QRect(200, 240, 141, 31))
        self.yapilanislemler.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.yapilanislemler.setObjectName("yapilanislemler")
        self.tutar = QtWidgets.QLabel(parent=self.widget)
        self.tutar.setGeometry(QtCore.QRect(200, 280, 141, 31))
        self.tutar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tutar.setObjectName("tutar")
        self.verticalLayout.addWidget(self.widget, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.plaka.setText(_translate("Form", "Plaka"))
        self.logo.setText(_translate("Form", "AY- CAR- TAKS"))
        self.sirasi.setText(_translate("Form", "Sırası"))
        self.yapilanislemler.setText(_translate("Form", "Yapılan İşlemler"))
        self.tutar.setText(_translate("Form", "Tutar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = musterigormesi()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
