# Form implementation generated from reading ui file 'şifremiunuttum.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class sifremiunuttum(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(542, 489)
        Form.setStyleSheet("#Form{\n"
"border-image: url(:/a/tamir3.jpg);\n"
"}")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(10, 10, 521, 471))
        self.widget.setObjectName("widget")
        self.logo = QtWidgets.QLabel(parent=self.widget)
        self.logo.setGeometry(QtCore.QRect(20, 90, 201, 291))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(46)
        font.setBold(False)
        self.logo.setFont(font)
        self.logo.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(85, 83, 84, 255), stop:1 rgba(255, 255, 255,110));")
        self.logo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.logo.setWordWrap(True)
        self.logo.setObjectName("logo")
        self.sorunyasama = QtWidgets.QLabel(parent=self.widget)
        self.sorunyasama.setGeometry(QtCore.QRect(260, 170, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setBold(True)
        self.sorunyasama.setFont(font)
        self.sorunyasama.setStyleSheet("background-color: rgb(237, 250, 123);")
        self.sorunyasama.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.sorunyasama.setObjectName("sorunyasama")
        self.eposta = QtWidgets.QLineEdit(parent=self.widget)
        self.eposta.setGeometry(QtCore.QRect(290, 230, 181, 22))
        self.eposta.setObjectName("eposta")
        self.giriskodu = QtWidgets.QPushButton(parent=self.widget)
        self.giriskodu.setGeometry(QtCore.QRect(290, 260, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        self.giriskodu.setFont(font)
        self.giriskodu.setStyleSheet("QPushButton#giriskodu{\n"
"    background-color: rgb(255, 255, 0);\n"
"    background-color: rgb(0, 126, 189);\n"
"\n"
"}\n"
"\n"
"QPushButton#giriskodu:pressed{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.giriskodu.setObjectName("giriskodu")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.logo.setText(_translate("Form", "AY- CAR- TAKS"))
        self.sorunyasama.setText(_translate("Form", "Giriş Yaparken Sorun mu Yaşıyorsun?"))
        self.eposta.setPlaceholderText(_translate("Form", "E-postanı gir"))
        self.giriskodu.setText(_translate("Form", "Giriş Kodu Gönder"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = sifremiunuttum()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
