# Form implementation generated from reading ui file 'yoneticiMenu.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class yoneticiMenu(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(602, 474)
        Form.setStyleSheet("#Form{\n"
"border-image: url(:/a/tamir3.jpg);\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.arabaEkleBT = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arabaEkleBT.sizePolicy().hasHeightForWidth())
        self.arabaEkleBT.setSizePolicy(sizePolicy)
        self.arabaEkleBT.setObjectName("arabaEkleBT")
        self.verticalLayout.addWidget(self.arabaEkleBT)
        self.arabaSilBT = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arabaSilBT.sizePolicy().hasHeightForWidth())
        self.arabaSilBT.setSizePolicy(sizePolicy)
        self.arabaSilBT.setObjectName("arabaSilBT")
        self.verticalLayout.addWidget(self.arabaSilBT)
        self.arabaIslemlerBT = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arabaIslemlerBT.sizePolicy().hasHeightForWidth())
        self.arabaIslemlerBT.setSizePolicy(sizePolicy)
        self.arabaIslemlerBT.setObjectName("arabaIslemlerBT")
        self.verticalLayout.addWidget(self.arabaIslemlerBT)
        self.cirakSilBT = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cirakSilBT.sizePolicy().hasHeightForWidth())
        self.cirakSilBT.setSizePolicy(sizePolicy)
        self.cirakSilBT.setObjectName("cirakSilBT")
        self.verticalLayout.addWidget(self.cirakSilBT)
        self.aciliyetArabaBT = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aciliyetArabaBT.sizePolicy().hasHeightForWidth())
        self.aciliyetArabaBT.setSizePolicy(sizePolicy)
        self.aciliyetArabaBT.setObjectName("aciliyetArabaBT")
        self.verticalLayout.addWidget(self.aciliyetArabaBT)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(4, 1)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 2)
        self.verticalLayout_2.setStretch(2, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.arabaEkleBT.setText(_translate("Form", "Araba Ekle"))
        self.arabaSilBT.setText(_translate("Form", "Araba Sil"))
        self.arabaIslemlerBT.setText(_translate("Form", "Araba İşlemleri"))
        self.cirakSilBT.setText(_translate("Form", "Çırak Sil"))
        self.aciliyetArabaBT.setText(_translate("Form", "Aciliyeti Olan Arabalar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = yoneticiMenu()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
