# Form implementation generated from reading ui file 'yonetici1.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class yonetici1(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(551, 494)
        Form.setStyleSheet("#Form{\n"
"border-image: url(:/a/tamir3.jpg);\n"
"\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setMinimumSize(QtCore.QSize(533, 476))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.logo = QtWidgets.QLabel(parent=self.widget)
        self.logo.setGeometry(QtCore.QRect(40, 90, 211, 291))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(46)
        font.setBold(False)
        self.logo.setFont(font)
        self.logo.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(85, 83, 84, 255), stop:1 rgba(255, 255, 255,110));")
        self.logo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.logo.setWordWrap(True)
        self.logo.setObjectName("logo")
        self.eposta = QtWidgets.QLineEdit(parent=self.widget)
        self.eposta.setGeometry(QtCore.QRect(290, 170, 211, 31))
        self.eposta.setObjectName("eposta")
        self.sifre = QtWidgets.QLineEdit(parent=self.widget)
        self.sifre.setGeometry(QtCore.QRect(290, 210, 211, 31))
        self.sifre.setObjectName("sifre")
        self.girisyap = QtWidgets.QPushButton(parent=self.widget)
        self.girisyap.setGeometry(QtCore.QRect(350, 250, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        self.girisyap.setFont(font)
        self.girisyap.setStyleSheet("QPushButton#girisyap{\n"
"    background-color: rgb(255, 255, 0);\n"
"    background-color: rgb(0, 126, 189);\n"
"\n"
"}\n"
"\n"
"QPushButton#girisyap:pressed{\n"
"     background-color: rgb(255, 255, 255);\n"
"}")
        self.girisyap.setObjectName("girisyap")
        self.label_5 = QtWidgets.QLabel(parent=self.widget)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 531, 471))
        self.label_5.setStyleSheet("")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.sifremiunuttum = QtWidgets.QPushButton(parent=self.widget)
        self.sifremiunuttum.setGeometry(QtCore.QRect(330, 290, 131, 24))
        self.sifremiunuttum.setStyleSheet("background-color: rgb(223, 223, 166);")
        self.sifremiunuttum.setObjectName("sifremiunuttum")
        self.eyesimge = QtWidgets.QPushButton(parent=self.widget)
        self.eyesimge.setGeometry(QtCore.QRect(460, 210, 41, 31))
        self.eyesimge.setStyleSheet("#eyesimge{\n"
"border-image: url(:/a/openEye.png);\n"
"}\n"
"\n"
"#eyesimge:pressed{\n"
"border-image: url(:/a/closedEye.png);\n"
"}")
        self.eyesimge.setText("")
        self.eyesimge.setObjectName("eyesimge")
        self.label_5.raise_()
        self.logo.raise_()
        self.eposta.raise_()
        self.sifre.raise_()
        self.girisyap.raise_()
        self.sifremiunuttum.raise_()
        self.eyesimge.raise_()
        self.verticalLayout.addWidget(self.widget, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.logo.setText(_translate("Form", "AY-CAR-TAKS"))
        self.eposta.setPlaceholderText(_translate("Form", "E-posta adresi"))
        self.sifre.setPlaceholderText(_translate("Form", "Şifre"))
        self.girisyap.setText(_translate("Form", "Giriş Yap"))
        self.sifremiunuttum.setText(_translate("Form", "  Şifreni mi unuttun?"))
